## 随机数种子
随机种子（Random Seed）是用于初始化随机数生成器的一个固定值。通过设置相同的随机种子，随机数生成器会产生相同的随机数序列，这对于实验和结果的可重复性至关重要。
常见的随机操作包括：
+ 数据集的随机拆分(如训练集和测试集的划分)
+ 模型参数的随机初始化
+ 数据增强中的随机变换

In [2]:
# example of setting random seed for reproducibility
# the results will be the same each time
import numpy as np
import random

seed = 66
np.random.seed(seed)
random.seed(seed)

random_matrix_first = np.random.randn(3, 3)
print(random_matrix_first)
random_data_one_first = random.random()
random_data_two_first = random.random()
print(random_data_one_first, random_data_two_first)

[[ 1.41561436 -1.0852864  -0.61630804]
 [-0.75691618  0.34704773  1.5564911 ]
 [-2.95634856  1.35908068  0.64834679]]
0.0708089270590726 0.43458775374134095


In [6]:
# example of not setting random seed
# the results will be different each time
import numpy as np
import random

random_matrix_second = np.random.randn(3, 3)
print(random_matrix_second)
random_data_one_second = random.random()
random_data_two_second = random.random()
print(random_data_one_second, random_data_two_second)

[[ 1.16813814  0.45637558  0.09738635]
 [-0.49153527  0.12930581 -2.02304008]
 [-1.97253238  0.0355577  -0.25578848]]
0.9265221867221619 0.49491787839107704
